// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMC0Z37E16p-slpaVe-dU4yC_kPWQHQ24',
    appId: '1:994526910613:web:a3cea5893910a56c65e39c',
    messagingSenderId: '994526910613',
    projectId: 'produtcs-719aa',
    authDomain: 'produtcs-719aa.firebaseapp.com',
    storageBucket: 'produtcs-719aa.appspot.com',
    measurementId: 'G-E96Z4BCSPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQC4O5k5_x9Yf5yR89li47Jkz6n2h96Yk',
    appId: '1:994526910613:android:47933381d0275b4865e39c',
    messagingSenderId: '994526910613',
    projectId: 'produtcs-719aa',
    storageBucket: 'produtcs-719aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFeNfORHUpDwQjZVxA02VegZnBgukHZAs',
    appId: '1:994526910613:ios:2b1d45a50c6beab565e39c',
    messagingSenderId: '994526910613',
    projectId: 'produtcs-719aa',
    storageBucket: 'produtcs-719aa.appspot.com',
    iosBundleId: 'com.codigocorrecto.integrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFeNfORHUpDwQjZVxA02VegZnBgukHZAs',
    appId: '1:994526910613:ios:2b1d45a50c6beab565e39c',
    messagingSenderId: '994526910613',
    projectId: 'produtcs-719aa',
    storageBucket: 'produtcs-719aa.appspot.com',
    iosBundleId: 'com.codigocorrecto.integrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMC0Z37E16p-slpaVe-dU4yC_kPWQHQ24',
    appId: '1:994526910613:web:0414bbf714aba3ac65e39c',
    messagingSenderId: '994526910613',
    projectId: 'produtcs-719aa',
    authDomain: 'produtcs-719aa.firebaseapp.com',
    storageBucket: 'produtcs-719aa.appspot.com',
    measurementId: 'G-4VVSKFXT18',
  );
}
